### ISSUE TITLE
Remove tickler command sub-labels on error

### ISSUE THREAD

**Issue by lehrblogger** [rosulek/gmail-tickler#10]
Currently, it only removes the main `TICKLER_LABEL`, and not any of the sub-labels. Is this intentional? In contrast, I see that they are all removed in `untickleThread`.

While some users might prefer to see the labels that were in conflict, most of the time I can easily remember/re-decide until when I want to snooze the thread. The current behavior is particularly frustrating on email clients (such as [Outlook on iOS](https://itunes.apple.com/app/id951937596)) that don't show the labels that a thread currently has. If I snooze a thread to time A, and then a new email in that thread bumps it back to my inbox, then I may snooze it to time B without realizing that it already has the label for time A. This will cause it to mysteriously appear in my inbox again and again, no matter how many times I try to snooze it. If the Tickler removed the conflicting labels, then the snooze would again succeed the third time.

I'm happy to fix this, but wanted to get some feedback first about whether it warrants a switch and/or should be the default.

**Comment by rosulek** [comment]
​I don't feel strongly about this, the issue seems tied to different email
clients. I'm not against it being a configurable option.
