### ISSUE TITLE
Moving conversation to label tickler/tomorrow are returned to label /tickler/finished

### ISSUE THREAD

**Issue by orschiro** [rosulek/gmail-tickler#3]
Dear @rosulek,

Thank you very much for this great script! I followed your setup steps and my tickler labels are successfully created. I moved a conversation to `tickler/tomorrow` in expectation that it would return to my inbox tomorrow. However, it is returned one hour later (project trigger?) with the label `tickler/finished`. 

Do you have any idea why?

Thanks!

Robert

**Comment by rosulek** [comment]
When you add "tickler/tomorrow" label to a thread, the "tomorrow" is
calculated relative to the last email in that thread. I'm guessing that in
this case, the last email in the thread is yesterday. So relative to that
email, "tomorrow" means today.

Obviously it would make more sense for the date to be computed relative to
_when the label was applied._ Unfortunately there is no easy way for my
script to know that information (as far as I can tell). You might want to
get in the habit of saying "tickler/friday" for example which will work
better, unless the conversation is more than a week old.

Mike

**Comment by orschiro** [comment]
Hi Mike,

>  I'm guessing that in this case, the last email in the thread is yesterday.

Indeed it was an email from yesterday. That makes sense. Thanks for your quick response!

I will get myself used to using absolute days. Still great script, love it! :)

**Comment by orschiro** [comment]
> "tickler/friday" for example which will work better, unless the conversation is more than a week old.

Just encountered this issue. How would you suggest to treat conversations that are older than one week?
