### ISSUE TITLE
getYear() call in date2str

### ISSUE THREAD

**Issue by Hamzehn** [rosulek/gmail-tickler#30]
Hi, thank you very much for sharing this very useful script. I tried installing it and noticed that I couldn't get it to work without changing the call to getYear() in the date2str function to getFullYear().

Dates were being converted to strings like '120-07-16'  (120 years from 1900 base) and were not being parsed correctly later on.

**Comment by rosulek** [comment]
Wow, good catch. Thanks for the report. This is a change with the new google apps script engine:

> https://developers.google.com/apps-script/guides/v8-runtime/migration#incompatibilities

The next commit will fix this.
