### ISSUE TITLE
Bundle as web app

### ISSUE THREAD

**Issue by orschiro** [rosulek/gmail-tickler#4]
> (Figure out how to) Bundle the script as a web app that others can add easily.

Wanted to share the following Chrome extension with you. Maybe you can take it as a reference to convert gmail-tickler into an easy installable Chrome extension:

https://chrome.google.com/webstore/detail/gmail-snooze/ajhdhpnafihkepjialgccenokkljdlaf

https://github.com/google/gmailsnooze

Warmly,

Robert

**Comment by rosulek** [comment]
merge with discussion at #25
