### ISSUE TITLE
Label support for may/1

### ISSUE THREAD

**Issue by orschiro** [rosulek/gmail-tickler#5]
Hi @rosulek,

Quick question: Let's say I want to schedule an email for a specific date, can I then use the following label to get a reminder on May, 1st?

```
may/1
```

I couldn't find this information in the Readme. 

Thanks!

Robert

**Comment by rosulek** [comment]
A label of "tickler/may1" or "tickler/may/1" should work.

**Comment by orschiro** [comment]
Thanks very much! I will try this one!
